### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by meequz** [bensnyde/py-arin-rws-api#1]
The code is not usable because a license is missing.

**Comment by buraglio** [comment]
Would you be willing to provide an actual use case command line example? Does the script take arguments or does it need to be adjusted to take the template data into account?

**Comment by meequz** [comment]
I'm talking about project license. py-arin-rws-api license. Like GPL, BSD, MIT, Apache. Without the license no one knows if the authors allow he/she to use the code, with what permissions and restrictions.

**Comment by bensnyde** [comment]
Hello,

You're free to use the library without any restrictions. I'll try to get
this posted to the repository this evening.

Thank you,
Benton

**Comment by buraglio** [comment]
Right, I meant to post my comment as a new thread and didn't.

**Comment by mryauch** [comment]
Benton,

Unfortunately the legal default is exclusive copyright.  We are unable to use, copy, distribute, modify, or share this resource until there is a license applied.  I see that there was a commit this year, but I still do not see a license.  I would like to use this code, however if there is no license I will have to rewrite my own from scratch.  Hopefully you are still active and able to do so.  It should really be quite quick on Github.

Thank you for your time,

Matthew

**Edit:** I have created a pull request for a LICENSE.txt file that includes the MIT license.  It is a license that goes along with the spirit of the comment "You're free to use the library without any restrictions." but protects the author from legal action.

> Hello,
> 
> You're free to use the library without any restrictions. I'll try to get
> this posted to the repository this evening.
> 
> Thank you,
> Benton

**Comment by bensnyde** [comment]
MIT license applied. Thanks!
