### ISSUE TITLE
Usage examples and how-to?

### ISSUE THREAD

**Issue by buraglio** [bensnyde/py-arin-rws-api#2]
Would you be willing to provide an actual use case command line example? Does the script take arguments or does it need to be adjusted to take the template data into account?

**Comment by bensnyde** [comment]
ARIN accepts reassignments via email or through its RESTful API. If you are
not a programmer, I would strongly recommend that you opt for the former.
This library isn't really designed for command line usage, but for
including in your Python programs.

More information can be found at
https://www.arin.net/resources/request/reassignments.html#swip

To utilize this Python client library, you simply need to instantiate the
object by passing your API key:

```
arin = Arin("API-XXXX-YYYY-ZZZZ-XXXX")
```

Then you would build the NETBLOCK payload:

```
netblock = NetBlockPayload("S", "example description", "XXX.15.219.0",
"XXX.15.219.31", "27")
```

Parameter 1: 'S' for reassignment
Parameter 2: A description for the subnet reassignment
Parameter 3: Subnet start
Parameter 4: Subnet end
Parameter 5: CIDR prefix

More information regarding NETBLOCK payloads can be found at
https://www.arin.net/resources/restfulpayloads.html#netblock

Then you'll need to build the NET payload:

```
net = NetPayload("", "YYYY", "", "NET-XXX-15-128-0-1", "YYYY-XXX-15-219-0",
"ASXXXX", netblock)
```

Parameter 1: A comment to display operational information about the
Customer (NOC hours, website, etc.)
Parameter 2: orgHandle
Parameter 3: customerHandle
Parameter 4: parentNetHandle
Parameter 5: netName
Parameter 6: originAS
Parameter 7: The above NETBLOCK payload

More information regarding NET payloads can be found at
https://www.arin.net/resources/restfulpayloads.html#net

Lastly, submit the reassignment request:

```
print arin.reassign_net("NET-XXX-15-128-0-1", net)
```

Benton

**Comment by buraglio** [comment]
OK, that parallels with my experience as well. I can write my own wrapper but I'm not sure it's worth the time since I need to reassign a huge amount of space quickly. I
ll'l probably just set up an rWHOIS server and do it that way.
